sudo mount system.img /mnt/loop
#Cleanup
sudo rm -rf /mnt/loop/system/system_ext/app/QtiTelephonyService/
sudo rm -rf /mnt/loop/system/system_ext/app/uceShimService/
sudo rm -rf /mnt/loop/system/system_ext/app/com.qualcomm.qti.services.secureui/
sudo rm -rf /mnt/loop/system/phh/huawei/
sudo rm -rf /mnt/loop/system/phh/bv9500plus-mtk-kpd.kl
sudo rm -rf /mnt/loop/system/phh/lenovo-synaptics_dsx.kl
sudo rm -rf /mnt/loop/system/phh/libnfc-nci-huawei.conf
sudo rm -rf /mnt/loop/system/phh/mimix3-gpio-keys.kl
sudo rm -rf /mnt/loop/system/phh/moto-uinput-egis.kl
sudo rm -rf /mnt/loop/system/phh/nokia-soc_gpio_keys.kl
sudo rm -rf /mnt/loop/system/phh/nubia-nubia_synaptics_dsx.kl
sudo rm -rf /mnt/loop/system/phh/oneplus6-synaptics_s3320.kl
sudo rm -rf /mnt/loop/system/phh/oppo-touchpanel.kl
sudo rm -rf /mnt/loop/system/phh/samsung-gpio_keys.kl
sudo rm -rf /mnt/loop/system/phh/samsung-sec_touchkey.kl
sudo rm -rf /mnt/loop/system/phh/samsung-sec_touchscreen.kl
sudo rm -rf /mnt/loop/system/phh/sony-gpio-keys.kl
sudo rm -rf /mnt/loop/system/phh/teracube2e-mtk-kpd.kl
sudo rm -rf /mnt/loop/system/phh/zf6-goodixfp.kl
sudo rm -rf /mnt/loop/system/phh/zf6-googlekey_input.kl
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmis2.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redminote9t.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redminote9s.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redminote9promax.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redminote9pro.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redminote7.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redminote6pro.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redminote5.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmik20pro-systemui.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmik20pro.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmigo.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmi10x5g.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmi9a.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmi8a.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmi8.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmi7onc.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmi7a.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmi6pro.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmi6a.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-redmi6.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-pocof1.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-miplay.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mipad4.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mimix3.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mimix2s.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mimax3.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mia2lite.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mia2.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mi11lite5g.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mi9se.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mi9.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mi8se.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mi8pro.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mi8lite.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mi8ee.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mi8.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-xiaomi-mi6x.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-unihertz-jelly2.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-umidigi-power.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-umidigi-A3S.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-teracube-v7101o.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-teracube-2e.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-tecno-camon11.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-teclast-t30.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-teclast-m30.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-sony-XZ3.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-sony-pdx213-systemui.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-sony-pdx213.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-sony-pdx206.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-sony-J9110.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-sharp-s2.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-S10q.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-S10pq.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-s10e.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-s9q.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-s9pq.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-n9q.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-j6.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-gta3xl.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-a80.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-a70.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-a60q.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-a51x.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-a51.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-a50.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-a40.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-a30.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-a20.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-a9.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-samsung-a7.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-realme-x2pro.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-realme-rmx3366-systemui.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-realme-rmx3366.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-realme-rmx2117-systemui.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-realme-rmx2117.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-realme-q3.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-realme-narzo10a.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-realme-c3.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-realme-c2.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-realme-6i.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-realme-6.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-razer-cheryl.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-oukitel-wp8pro.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-oppo-peqm00-systemui.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-oppo-peqm00.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-oneplus-op8-systemui.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-oneplus-op8.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-oneplus-op6t.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-oneplus-op6.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-oneplus-n200-systemui.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-oneplus-n200.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-nubia-z18mini.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-nokia-pnx-8.1-x7.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-nokia-pl2-6.1.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-nokia-pda_sprout-5.1plus-x5.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-nokia-nokia_4_2.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-nokia-drg-6.1plus-x6.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-nokia-ctl-7-1.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-nokia-b2n-7plus.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-razr.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-onehyper.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-one-action.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-one.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-g8power.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-g8plus.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-g8.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-g7play.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-g7.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-g6plus.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-g6play.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-g6.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-e5plus.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-moto-e5.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-meizu-m2181-systemui.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-meizu-m2181.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-mbi-s10-systemui.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-mbi-s10.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-lg-velvet.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-lg-v40.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-lg-g7.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-lge-mfh505glm-systemui.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-lge-mfh505glm.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-lenovo-z5.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-lenovo-s5pro.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-lenovo-s5.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-lenovo-k5pro.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-infinix-zero6.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-infinix-s4.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-infinix-note10pro.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-infinix-note8.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-infinix-note7.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-infinix-note5.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-WAS.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-VTR.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-STF.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-SHT.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-RNE.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-PRA.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-PIC.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-LLD.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-FIG.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-EML.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-DUK.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-COR.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-COL.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-CLT.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-BND.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-BKL.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-AUM.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-ATU.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-ARE.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei-ANE.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-huawei.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-htc-u12plus.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-htc-exodus1.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-fairphone-fp3.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-essential-ph_1.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-duoqin-qin2pro.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-blackview-bv9500plus.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-blackview-bv6900.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-asus-zenfonemaxshot.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-asus-zenfonemaxm2.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-asus-zenfonelivel1za550kl.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-asus-zenfone8.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-asus-zenfone5z.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-asus-zenfone5-10.apk
sudo rm -rf /mnt/loop/system/product/overlay/treble-overlay-asus-zenfone5.apk
#Hosts fix
sudo cp hosts /mnt/loop/system/etc
sudo chmod 644 /mnt/loop/system/etc/hosts
#Include GrapheneOS camera app
sudo cp GrapheneCam /mnt/loop/system/system_ext/priv_app
#Bootanimation fix
sudo rm -f /mnt/loop/system/product/media/bootanimation.zip
sudo mv /mnt/loop/system/product/media/bootanimation-dark.zip /mnt/loop/system/product/media/bootanimation.zip
sudo umount /mnt/loop

